config/routes.rb
Besocial::Application.routes.draw do
  devise_for :users

  resources :users, :except => [:new, :create] do
     post 'subscribe', :on => :member
     post 'unsubscribe', :on => :member
     resources :posts, :only => [:create, :destroy]
  end

  post    'posts/:id/comments' => 'comments#create', :as => :post_comments
  delete  'posts/:post_id/comments/:id' => 'comments#destroy', :as => :post_comment

  get "profile" => 'users#edit'
  get "news" => 'users#news'

  root :to => 'users#show'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates_presence_of :comment, :post, :user
  default_scope order("created_at asc")
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create

    #validation
    @post = Post.find(params[:id])
    @user = User.find(@post.user_id)
    @comment = Comment.new(params[:comment])
    @comment.post_id = @post.id
    @comment.user_id = current_user.id
    @comment.save
    respond_to do |format|
      format.html{ redirect_to user_path(@post.user_id) }
      format.js
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    authorize! :delete, @comment
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to user_path(@comment.post.user_id), :notice => "Comment was successfully deleted!" }
    end
  end
end

app/views/comments/_comment.html.erb
<div class="comment">
  <div class="author_avatar">
    <%= link_to image_tag(comment.user.avatar.url(:small), :class => 'avatar'), user_path(comment.user_id) %>
  </div>
  <div class="comment_info">
    <div class="author_name"><%= link_to comment.user.name, user_path(comment.user_id) %></div>
    <div class="message"><%= comment.comment %></div>
    <div class="time">
      <%= comment.created_at.strftime("%-d %b в %H:%M") %>
      <% if can? :delete, comment %>
          | <%= link_to "Удалить комментарий", post_comment_path(comment.post_id, comment.id), :method => :delete %>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/create.js.erb
$('#post<%= @comment.post_id%> .post_comments').append("<%= escape_javascript(render(:partial => 'comment', :locals => {:comment => @comment})) %>");