config/routes.rb
Besocial::Application.routes.draw do
  devise_for :users

  resources :users, :except => [:new, :create] do
     post 'subscribe', :on => :member
     post 'unsubscribe', :on => :member
     resources :posts, :only => [:create, :destroy]
  end

  post    'posts/:id/comments' => 'comments#create', :as => :post_comments
  delete  'posts/:post_id/comments/:id' => 'comments#destroy', :as => :post_comment

  get "profile" => 'users#edit'
  get "news" => 'users#news'

  root :to => 'users#show'

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :role
  has_many :wall_entries, :class_name => "Post", :dependent => :destroy
  has_many :posts, :foreign_key => :author_id

  has_many :subscriptions
  has_many :leaders, :through => :subscriptions
  has_many :subscribers, :class_name => 'Subscription', :foreign_key => 'leader_id'
  has_many :followers, :through => :subscribers, :source => :user

  has_many :news, :through => :leaders, :source => :posts

  has_attached_file :avatar, :styles => { :normal => "200", :small => "50x50#" }, :default_url => '/assets/missing_:style.jpg'

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :nick, :status,
                  :first_name, :last_name, :gender, :birthday, :about, :avatar

  validates_length_of :first_name, :last_name, :minimum => 1, :too_short => "should be at least 1 character"

  self.per_page = 15

  def admin?
    self.role && self.role.name == "admin"
  end

  def name
    self.first_name + ' ' + self.last_name
  end

  def subscribed_to?(user_id)
    self.leaders.exists?(user_id)
  end

  #def news
    #self.leaders.posts
  #end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource :only => [:destroy, :edit, :update]

  # GET /users
  #-----------------------------------------------------------------------
  def index
    @users = User.paginate(:page => params[:page])
    respond_to do |format|
      format.html{
        render(:layout => false) if request.xhr?
      }
    end
  end

  # GET /users/1
  #-------------------------------------------------------------------
  def show
    @user = params[:id] ? User.find(params[:id]) : current_user
    respond_to do |format|
      format.js {
        @wall = @user.wall_entries.paginate(:page => params[:page], :per_page => 15)
      }
      format.html{
        render(:layout => false) if request.xhr?
      }
    end
  end

  # GET /users/1/edit
  #-------------------------------------------------------------------
  def edit
    @user = params[:id] ? User.find(params[:id]) : current_user
    respond_to do |format|
      format.html
    end
  end

  # DELETE /users/1
  #-------------------------------------------------------------------
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_path, :notice => "User was successfully deleted!" }
    end
  end

  def update
    if params[:user][:password].blank?
      [:password,:password_confirmation,:current_password].collect{|p| params[:user].delete(p) }
    else
      @user.errors[:base] << "The password you entered is incorrect" unless @user.valid_password?(params[:user][:current_password])
    end

    respond_to do |format|
      if @user.errors[:base].empty? and @user.update_attributes(params[:user])
        flash[:notice] = "Your account has been updated"
        format.html { render :action => :edit }
      else
        format.html { render :action => :edit, :status => :unprocessable_entity }
      end
    end
  end

  def subscribe
    @subscription = current_user.subscriptions.create(:leader_id => params[:id])
    respond_to do |format|
      format.html {
        redirect_to user_path(params[:id]), :notice => (@subscription.errors.any? ? (@subscription.errors.full_messages * ',') : "You have successfully subscribed to this user.")
      }
      format.js {
        @user = User.find(params[:id])
        @subscribed = true
      }
    end
  end

  def unsubscribe
    @subscription = current_user.subscriptions.find_by_leader_id!(params[:id])
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to user_path(params[:id]) }
      format.js {
        @user = User.find(params[:id])
        @subscribed = false
        render :action => 'subscribe'
      }
    end
  end

  def news
    @news = current_user.news.paginate(:page => params[:page], :per_page => 15)
    respond_to do |format|
      format.js
      format.html{
        render(:layout => false) if request.xhr?
      }
    end
  end
end

app/views/users/_news_content.html.erb
<%= render(@news) || "<p>У вас нет новостей.</p>".html_safe %>
<%= will_paginate @news, :remote => true,  :renderer => 'RemoteLinkRenderer' %>

app/views/users/_subscribe.html.erb
<% unless @user.id == current_user.id %>
    <% if current_user.subscribed_to?(@user.id) %>
        <%= button_to 'Отписаться', unsubscribe_user_path(@user), :class => 'button', :remote => true %>
    <% else %>
        <%= button_to 'Подписаться', subscribe_user_path(@user), :class => 'button', :remote => true %>
    <% end %>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td class="check"><%= check_box_tag :user, user.id, false, :id => nil %></td>
  <td class="nick"><%= link_to image_tag(user.avatar.url(:small), :class => "avatar"), user_path(user.id)  %><%= user.last_name + " " + user.first_name %></td>
  <td>
    <%= user.last_sign_in_at %>
    <% if can? :manage, :users %>
    <div class="actions">
      <%=  link_to "", edit_user_path(user.id), :class => "action_edit" %>
      <%=  link_to "", user_path(user.id), :class => "action_delete", :method => :delete, :confirm => "Вы уверены, что хотите удалить этого пользователя?" %>
    </div>
    <% end %>
  </td>
</tr>

app/views/users/_wall_content.html.erb
<%= render(wall) || "<p>На вашей стене нет записей.</p>".html_safe %>
<%= will_paginate wall, :remote => true,  :renderer => 'RemoteLinkRenderer' %>

app/views/users/edit.html.erb
<%= form_for @user, :html => { :class => "user_form", :id => "edit_user", :multipart => true, :method => :put } do |f| %>
    <div id="sidebar">
      <%= image_tag @user.avatar.url(:normal), :class => "avatar" %>
      <span class="file-wrapper">
        <%= f.file_field :avatar %>
        <span class="button">Изменить фото</span>
      </span>
    </div>
    <div id="content" class="content">
      <h1>Редактировать профиль</h1>
      <div class="inner">
        <% if @user.errors.any? %>
            <div id="error_explanation">
              <ul>
                <% @user.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <div class="field"><%= f.label :nick, "Ник" %>
          <%= f.text_field :nick %></div>

        <div class="field"><%= f.label :status, "Статус" %>
          <%= f.text_field :status %></div>

        <div class="field"><%= f.label :first_name, "Имя" %>
          <%= f.text_field :first_name %></div>

        <div class="field"><%= f.label :last_name, "Фамилия" %>
          <%= f.text_field :last_name %></div>

        <div class="field"><label>ПОЛ</label>
          <%= f.radio_button :gender, true %>
          <%= f.label :gender, "Мужской", :class => "gender" %>
          <%= f.radio_button :gender, false %>
          <%= f.label :gender, "Женский", :class => "gender" %>
        </div>

        <div class="field"><%= f.label :birthday, "День рождения" %>
          <%= f.date_select :birthday, :start_year => 1930, :end_year => (Time.now.year - 5) %></div>

        <div class="field"><%= f.label :about, "О себе" %>
          <%= f.text_area :about %></div>

        <div class="field"><%= f.label :password, 'Пароль <span class="hint">(оставьте пустым если не хотите менять)</span>'.html_safe %>
          <%= f.password_field :password, :autocomplete => "off" %></div>

        <div class="field"><%= f.label :password_confirmation, "Повторите пароль" %>
          <%= f.password_field :password_confirmation %></div>

        <div class="field"><%= f.label :current_password, "Текущий пароль" %>
          <%= f.password_field :current_password %></div>

        <div class="field"><%= f.submit "Сохранить", :class => 'button' %></div>

      </div>
    </div>
<% end %>

app/views/users/index.html.erb
<div id="content" class="content">
  <h1>Пользователи</h1>
  <div class="inner">
    <%= form_for(users_path, :html => {:id => "users_form"}) do %>
        <table id="users_table" cellspacing="0" cellpadding="0">
          <thead>
          <tr>
            <td class="check"><%= check_box_tag :select_all %></td>
            <td class="nick">НИК</td>
            <td class="last_seen">ПОСЛЕДНИЙ ДОСТУП</td>
          </tr>
          </thead>
          <tbody>
          <%= render @users %>
          </tbody>
        </table>
        <%= will_paginate @users %>
        Выбранные: <%= select_tag "action", "<option>Выберите действие</option>".html_safe %>
        <%= submit_tag "Применить выбранное", :class => 'button' %>
    <% end %>
  </div>
</div>

app/views/users/news.html.erb
<div id="content" class="content news">
  <h1>Новостная лента</h1>
  <div class="inner">
      <%= render 'news_content' %>
  </div>
</div>

app/views/users/news.js.erb
$("#content .inner").html("<%= escape_javascript(render(:partial => 'news_content')) %>")

app/views/users/show.html.erb
<div id="sidebar">
  <%= image_tag @user.avatar.url(:normal), :class => "avatar" %>
  <div id="subscribe">
    <%= render 'subscribe' %>
  </div>
  <h2>Подписчики</h2>
  <div class="content inner">
    <% if @user.followers.count > 0 %>
      <ul id="followers">
        <% @user.followers.each do |follower| %>
          <li>
            <%= link_to image_tag(follower.avatar.url(:small), :class => 'avatar'), user_path(follower) %>
            <div class="name"><%= link_to follower.name, user_path(follower) %></div>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>This user has no subscribers.</p>
    <% end %>
  </div>
</div>
<div id="content">
  <div id="info" class="content inner">
    <h2><%= @user.last_name %> <%= @user.first_name %></h2>
    <div class="status">
      <%= @user.status %>
    </div>
    <div class="sep"></div>
    <dl class="profile">
      <dt>День рождения:</dt><dd><%= @user.birthday ? @user.birthday.strftime("%-d %B %Y") : "не указан" %></dd>
      <dt>Пол:</dt><dd><%= @user.gender ? "Мужской" : "Женский" %></dd>
      <dt>О себе:</dt><dd><%= @user.about %></dd>
    </dl>
  </div>
  <div class="content">
    <h1>Стена</h1>
    <% @new_post = @user.wall_entries.build %>
    <% @new_post.pictures.build %>
    <%= form_for @new_post, :url => user_posts_path(@user.id), :class => 'new_post', :remote => true, :multipart => true do |f| %>
        <%= f.text_area :message %>
        <span class="file-wrapper">
          <%= f.fields_for :pictures do |p| %>
            <%= p.file_field 'picture' %>
          <% end %>
          <span class="button">ПРИКРЕПИТЬ</span>
        </span>
        <ul id="pending_list"></ul>
        <%= f.submit "Отправить", :class => 'button' %>
    <% end %>
    <div class="inner wall">
        <%= render :partial => 'wall_content', :locals => {:wall => @user.wall_entries.paginate(:page => params[:page], :per_page => 15)} %>
    </div>
  </div>

</div>

app/views/users/show.js.erb
$("#content .wall").html("<%= escape_javascript(render(:partial => 'wall_content', :locals => {:wall => @wall})) %>")

app/views/users/show_page.html.erb
<div id="sidebar">
  <%= image_tag @user.avatar.url(:normal), :class => "avatar" %>
  <div id="subscribe">
    <%= render 'subscribe' %>
  </div>
  <h2>Подписчики</h2>
  <div class="content inner">
    <% if @user.followers.count > 0 %>
      <ul id="followers">
        <% @user.followers.each do |follower| %>
          <li>
            <%= link_to image_tag(follower.avatar.url(:small), :class => 'avatar'), user_path(follower) %>
            <div class="name"><%= link_to follower.name, user_path(follower) %></div>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>This user has no subscribers.</p>
    <% end %>
  </div>
</div>
<div id="content">
  <div id="info" class="content inner">
    <h2><%= @user.last_name %> <%= @user.first_name %></h2>
    <div class="status">
      <%= @user.status %>
    </div>
    <div class="sep"></div>
    <dl class="profile">
      <dt>День рождения:</dt><dd><%= @user.birthday ? @user.birthday.strftime("%-d %B %Y") : "не указан" %></dd>
      <dt>Пол:</dt><dd><%= @user.gender ? "Мужской" : "Женский" %></dd>
      <dt>О себе:</dt><dd><%= @user.about %></dd>
    </dl>
  </div>
  <div class="content">
    <h1>Стена</h1>
    <%= form_tag user_posts_path(@user),:class => 'new_post', :multipart => true do |f| %>
        <%= text_area_tag :message %>
        <span class="file-wrapper">
                <%= file_field_tag 'pictures[]' %>
          <span class="button">ПРИКРЕПИТЬ</span>
            </span>
        <%= submit_tag "Отправить", :class => 'button' %>
    <% end %>
    <div class="inner wall">
        <%= render :partial => 'wall_content', :locals => {:wall => @user.wall_entries.paginate(:page => params[:page], :per_page => 2)} %>
    </div>
  </div>

</div>

app/views/users/show_page.js.erb
$("#content .wall").html("<%= escape_javascript(render(:partial => 'wall_content', :locals => {:wall => @wall})) %>")

app/views/users/subscribe.js.erb
<% if @subscription.errors.empty? %>
$("#subscribe").html("<%= escape_javascript(render(:partial => 'subscribe')) %>");
<% end %>
$("#notice")
        .html("<%= @subscription.errors.any? ? (@subscription.errors.full_messages * ',') : ("You have successfully " + (@subscribed ? "subscribed" : "unsubscribed") + " to this user.") %>")
        .fadeIn()
        .delay(3000).fadeOut();