config/routes.rb
Besocial::Application.routes.draw do
  devise_for :users

  resources :users, :except => [:new, :create] do
     post 'subscribe', :on => :member
     post 'unsubscribe', :on => :member
     resources :posts, :only => [:create, :destroy]
  end

  post    'posts/:id/comments' => 'comments#create', :as => :post_comments
  delete  'posts/:post_id/comments/:id' => 'comments#destroy', :as => :post_comment

  get "profile" => 'users#edit'
  get "news" => 'users#news'

  root :to => 'users#show'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, :class_name => "User", :foreign_key => :author_id
  belongs_to :user

  has_many :pictures, :dependent => :destroy
  has_many :comments, :dependent => :destroy

  validates_existence_of :user
  validates_existence_of :author

  #validates_length_of :message, :minimum => 1, :too_short => "please enter at least 1 character"

  accepts_nested_attributes_for :pictures

  default_scope order("updated_at desc")


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def create
        @post = Post.new(params[:post])
        @post.user_id = params[:user_id]
        @post.author_id = current_user.id
        @post.save
        flash[:notice] =  @post.errors.any? ? ("Please correct errors: " + @post.errors.full_messages * ',') : "Post was successfully created"
        respond_to do |format|
          format.html {
            redirect_to user_path(:id => params[:user_id])
          }
          format.js{
            @user = User.find(params[:user_id])
            @wall = @user.wall_entries.paginate(:page => params[:page], :per_page => 15)
          }
        end
    end

    def destroy
      @post = Post.find(params[:id])
      authorize! :delete, @post
      @post.destroy
      redirect_to user_path(params[:user_id]), :notice => "Post was successfully deleted!"
    end
end

app/views/posts/_post.html.erb
<div class="post" id="post<%= post.id %>">
    <div class="author_avatar">
        <%= link_to image_tag(post.author.avatar.url(:small), :class => 'avatar'), user_path(post.author.id) %>
    </div>
    <div class="post_info">
        <div class="author_name"><%= link_to post.author.name, user_path(post.author_id) %></div>
        <div class="post_message">
            <%= post.message %>
            <%= render post.pictures %>
        </div>
        <div class="time">
          <%= post.updated_at.strftime("%-d %b в %H:%M") %>
          <% if can? :delete, post %>
          | <%= link_to "Удалить запись", user_post_path(post.user.id, post.id), :method => :delete %>
          <% end %>
        </div>
        <div class="post_comments">
            <%= render post.comments %>
        </div>
        <% new_comment = post.comments.build %>
        <%= form_for new_comment, :url => post_comments_path(new_comment.post_id), :remote => true do |f| %>
            <%= f.text_area :comment, :size => '78x2' %>
            <%= f.submit "Комментировать", :class => 'button' %>
        <% end %>
    </div>
</div>

app/views/posts/create.js.erb
<% if @post.errors.empty? %>
$("#new_post").clearForm();
$("#content .wall").html("<%= escape_javascript(render(:partial => 'users/wall_content', :locals => {:wall => @wall})) %>")
<% end %>
$("#notice")
        .html("<%= flash[:notice] %>")
        .fadeIn()
        .delay(3000).fadeOut();