config/routes.rb
Besocial::Application.routes.draw do
  devise_for :users

  resources :users, :except => [:new, :create] do
     post 'subscribe', :on => :member
     post 'unsubscribe', :on => :member
     resources :posts, :only => [:create, :destroy]
  end

  post    'posts/:id/comments' => 'comments#create', :as => :post_comments
  delete  'posts/:post_id/comments/:id' => 'comments#destroy', :as => :post_comment

  get "profile" => 'users#edit'
  get "news" => 'users#news'

  root :to => 'users#show'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Besocial</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div id="top_panel_wrap">
        <div id="top_panel">
          <div class="wrapper">
            <% if user_signed_in? %>
              <%= link_to t('.top_panel.my_page'), root_path, :class => "home" %>
              <span class="sep"></span>
              <%= link_to t('.top_panel.profile'), profile_path, :class => "profile" %>
              <%= link_to t('.top_panel.logout'), destroy_user_session_path, :method => :delete, :class => "logout", :confirm => t('.top_panel.logout_confirm') %>
            <% else %>
              <%= render "devise/links" %>
            <% end %>
          </div>
        </div>
    </div>
    <div id="header" class="wrapper">
      <div id="logo">
        <%=  link_to image_tag("logo.png"), 'http://rezonans.ru' %>
      </div>
      <% if user_signed_in? %>
        <div id="tab_controls">
          <%= link_to t('.tab_controls.my_page'), root_path, :class => "tab me"+ (current_page?( :controller => 'home', :action => 'index') ? " active":""), :remote => true %>
          <%= link_to t('.tab_controls.users'), users_path, :class => "tab users"+(current_page?( :controller => 'users', :action => 'index')  ? " active":"") %>
          <%= link_to t('.tab_controls.news'), news_path, :class => "tab news"+(current_page?( :controller => 'home', :action => 'news')  ? " active":"") %>
        </div>
      <% else %>
        <% if controller_name == 'sessions' %>
          <div id="page_title" class="login">
            <h1><%= t('.page_title.login.caption') %></h1>
            <div class="hint"><%= t('.page_title.login.hint') %></div>
          </div>
        <% end %>
        <% if controller_name == 'registrations' %>
          <div id="page_title" class="login">
            <h1><%= t('.page_title.registration.caption') %></h1>
            <div class="hint"><%= t('.page_title.registration.hint') %></div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div id="main">
        <div class="wrapper">
          <% if flash[:warning] or flash[:notice] %>
            <div id="notice">
              <%= flash[:warning] || flash[:notice] %>
            </div>
          <% else %>
            <div id="notice" style="display: none"></div>
          <% end %>
        <%= yield %>
        </div>
    </div>
    <div id="footer">
         &copy; Copyright 2012 <%= link_to "Rezonans.ru", "http://rezonans.ru" %>. All rights reserved.
    </div>
</body>
</html>